env:
  ES_ENDPOINT: https://localhost:9200
  ES_USERNAME: admin
  ES_PASSWORD: $[[keystore.ES_PASSWORD]]
  WEB_BINDING: 0.0.0.0:9000
  API_BINDING: 0.0.0.0:2900

coco:
  server:
    public: false
    name: "My Coco Server"
    encode_icon_to_base64: false # enable this if coco-server is using self-signed certs
#    #[START] for managed mode only, need to configured by coco-server operator
#    endpoint: "http://localhost:9001/"
#    auth_provider: #config for app to use
#      sso:
#        url: "http://localhost:9001/#/login"
#    #[END] for managed mode only
    minimal_client_version:
      number: "0.3"
    provider:
      name: "INFINI Labs"
      description: "Coco AI Server - Search, Connect, Collaborate, AI-powered enterprise search, all in one space."
      icon: "https://coco.rs/favicon.ico"
      website: "https://coco.rs/"
      eula: "https://coco.rs/#/terms"
      privacy_policy: "https://coco.rs/privacy"
      banner: "https://coco.rs/svg/connect.svg"
    store:
      endpoint: "https://coco.infini.cloud"
      enabled: true

## Cleanup exists data:
# curl -u admin:45ff432a5428ade77c7b -k -XDELETE   https://localhost:9200/_template/coco-search
# curl -u admin:45ff432a5428ade77c7b -k -XDELETE   https://localhost:9200/_template/coco
# curl -u admin:45ff432a5428ade77c7b -k -XDELETE  https://localhost:9200/_scripts/coco-query-string
# curl -u admin:45ff432a5428ade77c7b -k -XDELETE  https://localhost:9200/_scripts/coco-query-string-extra-should
# curl -u admin:45ff432a5428ade77c7b -k -XDELETE   https://localhost:9200/coco_*
elastic:
  elasticsearch: prod
  enabled: true
  store:
    enabled: false
  orm:
    enabled: true
    index_prefix: "coco_"
    override_exists_template: true
    override_exists_mapping: true
    index_templates:
      "coco-search": |
        {
          "order": 10,
          "index_patterns": [
            "coco_*"
          ],
          "settings": {
            "index": {
              "analysis": {
                "char_filter": {
                    "tsconvert" : {
                        "type" : "stconvert",
                        "delimiter" : ",",
                        "keep_both" : false,
                        "convert_type" : "t2s"
                    }
                 },
                "tokenizer": {
                      "my_pinyin": {
                        "type": "pinyin",
                        "keep_first_letter": true,
                        "keep_separate_first_letter": true,
                        "keep_full_pinyin": true,
                        "keep_original": false,
                        "limit_first_letter_length": 16,
                        "lowercase": true
                      }
                    },
                "analyzer": {
                  "pinyin_analyzer": {
                     "tokenizer": "my_pinyin"
                   },
                  "combined_text_analyzer": {
                    "char_filter": ["tsconvert"],
                    "filter": [
                      "lowercase",
                      "asciifolding",
                      "word_delimiter",
                      "unique"
                    ],
                    "tokenizer": "classic"
                  }
                }
              }
            }
          },
          "mappings": {}
        }


elasticsearch:
  - name: prod
    enabled: true
    endpoints:
      - $[[env.ES_ENDPOINT]]
    discovery:
      enabled: false
    basic_auth:
      username: $[[env.ES_USERNAME]]
      password: $[[env.ES_PASSWORD]]

api:
  enabled: true
  websocket:
    enabled: false
  network:
    binding: $[[env.API_BINDING]]

web:
#  base_path: "/coco"
  enabled: true
  embedding_api: false
  network:
    binding: $[[env.WEB_BINDING]]
  tls:
    enabled: false
    skip_insecure_verify: true
    default_domain: "localhost:2900"
    #    default_domain: "api.coco.rs"
    auto_issue:
      enabled: false
      email: "hello@infinilabs.com"
      include_default_domain: true
      domains:
        - "www.coco.rs"
      provider:
        tencent_dns:
          secret_id: $[[keystore.TENCENT_DNS_ID]] #./bin/coco keystore add TENCENT_DNS_ID
          secret_key: $[[keystore.TENCENT_DNS_KEY]] #./bin/coco keystore add TENCENT_DNS_KEY
  security:
    enabled: true
    managed: false #remote managed instance
    authentication:
      native:
        enabled: true
      access_token:
        enabled: true
        native: true
      oauth:
        cloud:
          enabled: true
          client_secret: "999999"
          authorize_url: "http://localhost:9000/oauth/authorize"
          token_url: "http://localhost:9000/oauth/token"
          profile_url: "http://localhost:9000/account/profile"
          redirect_url: "http://localhost:9001/sso/callback/cloud"
          success_page: "/#/home"
          failed_page: "/#/login"
          scopes: [ "openid","email","profile" ]
    authorization:
      native:
        enabled: true

##background jobs
pipeline:
  - name: process_documents
    enabled: true
    auto_start: true
    keep_running: true
    processor:
      - consumer:
          auto_commit_offset: true
          queue_selector:
            keys:
              - indexing_documents
          consumer:
            group: enriched_documents
            fetch_max_messages: 10
          processor:
            - process_documents:
                output_queue:
                      name: "documents_processed"

  - name: process_attachments
    enabled: true
    auto_start: true
    keep_running: true
    processor:
      - consumer:
          auto_commit_offset: true
          queue_selector:
            keys:
              - attachment_processing
          consumer:
            group: process_attachments
            fetch_max_messages: 10
          processor:
            - process_attachments: {}

  - name: merge_documents
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: documents_processed
          idle_timeout_in_seconds: 1
          elasticsearch: "prod"
          index_name: "coco_document-v2"
          key_field: "id"
          output_queue:
            name: "merged_documents"
            label:
              tag: "merged"
          worker_size: 1
          bulk_size_in_kb: 10240
  - name: ingest_documents
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 10240
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
            tag: "merged"

  - name: connector_dispatcher
    auto_start: true
    keep_running: true
    singleton: true
    retry_delay_in_ms: 10000
    processor:
      - connector_dispatcher:
          max_running_timeout_in_seconds: 1200
#          pipelines_in_sync: true

http_client:
  default:
    proxy:
      enabled: false
      default_config:
        http_proxy: http://127.0.0.1:7890
        socket5_proxy: socks5://127.0.0.1:7890
      override_system_proxy_env: true #override system proxy's environment settings with this proxy settings
      permitted:
        - "google.com"
      denied:
        - "localhost"
        - "www.yuque.com"
        - "yuque.com"
        - "infinilabs.com"
        - "api.coco.rs"
        - "dashscope.aliyuncs.com"
      domains:
        "github.com":
          http_proxy: http://127.0.0.1:7890
          socket5_proxy: socks5://127.0.0.1:7890

field_metadata:
  "title.keyword":
    field_icon: "font_docs"
    field_label: "Title"
    field_description:
      en: "Document title"
      zh: "文档标题"
    field_name: "title.keyword"
    field_data_type: "keyword"
    support_multi_select: false

  type:
    field_icon: "font_filetype-txt"
    field_label: "Type"
    field_description:
      en: "Document type (e.g., PDF, Docx)"
      zh: "文档类型（如 PDF、Docx）"
    field_name: "type"
    field_data_type: "keyword"
    support_multi_select: true

  category:
    field_icon: "font_filetype-folder"
    field_label: "Category"
    field_description:
      en: "Primary category of the document"
      zh: "文档的主分类"
    field_name: "category"
    field_data_type: "keyword"
    support_multi_select: true

  subcategory:
    field_icon: "font_filetype-folder"
    field_label: "Subcategory"
    field_description:
      en: "Secondary category of the document"
      zh: "文档的子分类"
    field_name: "subcategory"
    field_data_type: "keyword"
    support_multi_select: true

  categories:
    field_icon: "font_filetype-folder"
    field_label: "Categories"
    field_description:
      en: "Full hierarchy of categories"
      zh: "完整的分类层级"
    field_name: "categories"
    field_data_type: "keyword"
    support_multi_select: true

  lang:
    field_icon: "font_Translation"
    field_label: "Language"
    field_description:
      en: "Language code (e.g., en, zh)"
      zh: "语言代码（如 en、zh）"
    field_name: "lang"
    field_data_type: "keyword"
    support_multi_select: true

  tags:
    field_icon: "font_Efficiency"
    field_label: "Tags"
    field_description:
      en: "Tags or keywords for easier retrieval"
      zh: "便于检索的标签或关键词"
    field_name: "tags"
    field_data_type: "keyword"
    support_multi_select: true

  "source.type":
    field_icon: "font_database"
    field_label: "Source Type"
    field_description:
      en: "Type of datasource (e.g., connector)"
      zh: "数据源类型（如连接器）"
    field_name: "source.type"
    field_data_type: "keyword"
    support_multi_select: true

  "source.name":
    field_icon: "font_Googledrive"
    field_label: "Source Name"
    field_description:
      en: "Name of the datasource"
      zh: "数据源名称"
    field_name: "source.name"
    field_data_type: "keyword"
    support_multi_select: true

  "owner.name":
    field_icon: "font_Member"
    field_label: "Owner"
    field_description:
      en: "Document author or owner"
      zh: "文档作者或所有者"
    field_name: "owner.name"
    field_data_type: "keyword"
    support_multi_select: true