/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ai-assistant',
    path: '/ai-assistant',
    component: 'layout.base$view.ai-assistant',
    meta: {
      i18nKey: 'route.ai-assistant',
      title: 'ai-assistant',
      icon: 'mdi:robot-outline',
      order: 2
    }
  },
  {
    name: 'data-source',
    path: '/data-source',
    component: 'layout.base$view.data-source',
    meta: {
      i18nKey: 'route.data-source',
      title: 'data-source',
      icon: 'mdi:folder-open-outline',
      order: 3
    }
  },
  {
    name: 'guide',
    path: '/guide',
    component: 'layout.blank$view.guide',
    meta: {
      title: 'guide',
      i18nKey: 'route.guide',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      i18nKey: 'route.home',
      title: 'home',
      icon: 'mdi:home',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      i18nKey: 'route.settings',
      title: 'settings',
      icon: 'mdi:settings-outline',
      order: 4
    }
  }
];
