/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ai-assistant',
    path: '/ai-assistant',
    component: 'layout.base$view.ai-assistant',
    meta: {
      i18nKey: 'route.ai-assistant',
      title: 'ai-assistant',
      icon: 'mdi:robot-outline',
      order: 2
    }
  },
  {
    name: 'data-source',
    path: '/data-source',
    component: 'layout.base',
    redirect: 'list',
    meta: {
      i18nKey: 'route.data-source',
      title: 'data-source',
      icon: 'mdi:folder-open-outline',
      order: 3
    },
    children: [
      {
        name: 'data-source_detail',
        path: 'detail/:id',
        component: 'view.data-source_detail',
        meta: {
          i18nKey: 'route.data-source_detail',
          title: 'data-source_detail',
          hideInMenu: true,
          activeMenu: 'data-source'
        }
      },
      {
        name: 'data-source_list',
        path: 'list',
        component: 'view.data-source_list',
        meta: {
          i18nKey: 'route.data-source_list',
          title: 'data-source_list',
          hideInMenu: true,
          activeMenu: 'data-source'
        }
      },
      {
        name: 'data-source_new',
        path: 'new',
        component: 'view.data-source_new',
        meta: {
          i18nKey: 'route.data-source_new',
          title: 'data-source_new',
          hideInMenu: true,
          activeMenu: 'data-source'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank',
    redirect: 'pwd-login',
    layout: 'blank',
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    },
    children: [
      {
        name: 'login_code-login',
        path: 'code-login',
        component: 'view.login_code-login',
        meta: {
          title: 'login_code-login',
          i18nKey: 'route.login_code-login'
        }
      },
      {
        name: 'login_pwd-login',
        path: 'pwd-login',
        component: 'view.login_pwd-login',
        meta: {
          title: 'login_pwd-login',
          i18nKey: 'route.login_pwd-login'
        }
      },
      {
        name: 'login_register',
        path: 'register',
        component: 'view.login_register',
        meta: {
          title: 'login_register',
          i18nKey: 'route.login_register'
        }
      },
      {
        name: 'login_reset-pwd',
        path: 'reset-pwd',
        component: 'view.login_reset-pwd',
        meta: {
          title: 'login_reset-pwd',
          i18nKey: 'route.login_reset-pwd'
        }
      }
    ]
  },
  {
    name: 'server',
    path: '/server',
    component: 'layout.base$view.server',
    meta: {
      i18nKey: 'route.server',
      title: 'server',
      icon: 'mdi:server-outline',
      order: 1
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      i18nKey: 'route.settings',
      title: 'settings',
      icon: 'mdi:settings-outline',
      order: 4
    }
  }
];
