/* Copyright © INFINI LTD. All rights reserved.
 * Web: https://infinilabs.com
 * Email: hello#infini.ltd */

package hugo_site

import (
	"fmt"
	"net/url"
	"strings"
	"time"
)

type HugoDocument struct {
	Category    string   `json:"category,omitempty"`    // The main category of the document
	Content     string   `json:"content,omitempty"`     // The content description
	Subcategory string   `json:"subcategory,omitempty"` // The subcategory of the document
	Summary     string   `json:"summary,omitempty"`     // A brief summary
	Tags        []string `json:"tags,omitempty"`        // Tags associated with the document
	Title       string   `json:"title,omitempty"`       // The title of the document
	URL         string   `json:"url,omitempty"`         // The URL for the document reference
	Created     string   `json:"created,omitempty"`
	Updated     string   `json:"updated,omitempty"`
	Lang        string   `json:"lang,omitempty"`
}

type Config struct {
	Urls []string `json:"urls" config:"urls"`
}

// ParseTimestamp safely parses a timestamp string into a *time.Time.
// Returns nil if parsing fails.
func ParseTimestamp(timestamp string) *time.Time {
	layout := time.RFC3339 // ISO 8601 format
	parsedTime, err := time.Parse(layout, timestamp)
	if err != nil {
		return nil
	}
	return &parsedTime
}

// getFullURL normalizes a document URL from a Hugo JSON feed.
//
// Hugo feeds are inconsistent: some emit site-relative paths such as
// "/posts/hello", while others emit fully qualified URLs such as
// "https://example.com/posts/hello". This helper handles both forms.
//
// Relative URLs are resolved against the site root ("scheme://host/")
// rather than the feed's parent path. Whetehr this behavior is correct
// depends on how index.json is generated by Hugo. Currently, we are not
// sure about this as all the hugo versions we tested generate absolute
// URLs.
func getFullURL(seedURL, rawURL string) (string, error) {
	baseURL, err := url.Parse(seedURL)
	if err != nil {
		return "", fmt.Errorf("invalid seed URL: %w", err)
	}

	rawURL = strings.TrimSpace(rawURL)
	if rawURL == "" {
		return "", nil
	}

	docURL, err := url.Parse(rawURL)
	if err != nil {
		return "", fmt.Errorf("invalid document URL %q: %w", rawURL, err)
	}

	if docURL.IsAbs() {
		return docURL.String(), nil
	}

	siteRoot := &url.URL{Scheme: baseURL.Scheme, Host: baseURL.Host, Path: "/"}
	return siteRoot.ResolveReference(docURL).String(), nil
}
