POST $[[SETUP_INDEX_PREFIX]]app-roles/$[[SETUP_DOC_TYPE]]/d47m4df3edbo74oibebg
{
          "id": "d47m4df3edbo74oibebg",
          "created": "2025-11-08T23:31:01.927656+08:00",
          "updated": "2025-11-08T23:31:01.927656+08:00",
           "_system": {
                      "owner_id": "$[[SETUP_OWNER_ID]]"
                    },
          "name": "Guest",
          "description": "",
          "grants": {
            "permissions": [
               "coco#connector/read",
                "coco#datasource/read",
                "coco#document/read",
                "coco#integration/read",
                "coco#mcp_server/read",
                "coco#model_provider/read",
                "coco#system/read",
                "generic#entity:card/read",
                "generic#entity:label/read",
                "generic#security:authorization/read",
                "generic#security:permission/read",
                "generic#security:principal/search",
                "generic#security:role/read",
                "generic#security:user/read",
                "generic#sharing/read",
                "coco#assistant/read",
                "coco#assistant/search",
                "coco#session/create",
                "coco#session/read",
                "coco#session/search",
                "coco#session/view_single_session_history",
                "coco#assistant/ask",
                "coco#search/search",
                "coco#datasource/search",
                "coco#connector/search",
                "coco#document/search",
                "coco#mcp_server/search"
            ]
          }
}

POST $[[SETUP_INDEX_PREFIX]]app-roles/$[[SETUP_DOC_TYPE]]/d47m83v3edbo74oibfc0
{
          "id": "d47m83v3edbo74oibfc0",
          "created": "2025-11-08T23:38:55.688787+08:00",
          "updated": "2025-11-08T23:38:55.688787+08:00",
     "_system": {
                "owner_id": "$[[SETUP_OWNER_ID]]"
              },
          "name": "All",
          "description": "",
          "grants": {
            "permissions": [
              "coco#assistant/ask",
              "coco#assistant/create",
              "coco#assistant/delete",
              "coco#assistant/quick_ai_access",
              "coco#assistant/read",
              "coco#assistant/search",
              "coco#assistant/update",
              "coco#attachment/create",
              "coco#attachment/delete",
              "coco#attachment/read",
              "coco#attachment/search",
              "coco#attachment/update",
              "coco#connector/create",
              "coco#connector/delete",
              "coco#connector/read",
              "coco#connector/search",
              "coco#connector/update",
              "coco#datasource/create",
              "coco#datasource/delete",
              "coco#datasource/read",
              "coco#datasource/search",
              "coco#datasource/update",
              "coco#document/create",
              "coco#document/delete",
              "coco#document/read",
              "coco#document/search",
              "coco#document/update",
              "coco#integration/create",
              "coco#integration/delete",
              "coco#integration/read",
              "coco#integration/search",
              "coco#integration/update",
              "coco#integration/update_suggest_topics",
              "coco#integration/view_suggest_topics",
              "coco#mcp_server/create",
              "coco#mcp_server/delete",
              "coco#mcp_server/read",
              "coco#mcp_server/search",
              "coco#mcp_server/update",
              "coco#model_provider/create",
              "coco#model_provider/delete",
              "coco#model_provider/read",
              "coco#model_provider/search",
              "coco#model_provider/update",
              "coco#search/search",
              "coco#session/create",
              "coco#session/delete",
              "coco#session/read",
              "coco#session/search",
              "coco#session/update",
              "coco#session/view_all_session_history",
              "coco#session/view_single_session_history",
              "coco#store:extensions/create",
              "coco#store:extensions/delete",
              "coco#store:extensions/read",
              "coco#store:extensions/reindex",
              "coco#store:extensions/search",
              "coco#store:extensions/update",
              "coco#system/read",
              "coco#system/update",
              "generic#entity:card/read",
              "generic#entity:label/read",
              "generic#security:auth:api-token/create",
              "generic#security:auth:api-token/delete",
              "generic#security:auth:api-token/search",
              "generic#security:auth:api-token/update",
              "generic#security:authorization/create",
              "generic#security:authorization/delete",
              "generic#security:authorization/read",
              "generic#security:authorization/search",
              "generic#security:authorization/update",
              "generic#security:permission/read",
              "generic#security:principal/search",
              "generic#security:principal/update",
              "generic#security:role/create",
              "generic#security:role/delete",
              "generic#security:role/read",
              "generic#security:role/search",
              "generic#security:role/update",
              "generic#security:user/create",
              "generic#security:user/delete",
              "generic#security:user/read",
              "generic#security:user/search",
              "generic#security:user/update",
              "generic#sharing/create",
              "generic#sharing/delete",
              "generic#sharing/read",
              "generic#sharing/search",
              "generic#sharing/update"
            ]
          }
}